<a href="https://colab.research.google.com/github/nazaninzareirad/SVM-paper/blob/main/KernelApproxiation_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn import datasets as sk_datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.pipeline import make_pipeline
from sklearn.kernel_approximation import Nystroem
from sklearn.datasets import make_circles, fetch_openml
from sklearn.metrics import accuracy_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [ ]:
datasets = {
    'abalone': ('abalone', 'target'),
    'image': ('segment', 'class'),
    'pima': ('diabetes', 'class'),
    'waveform': ('waveform-5000', 'class')
}

# Abalone dataset

In [ ]:
from sklearn import svm
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import pandas as pd

data_name = 'abalone'
print(f"Processing dataset: {data_name}")

mode = 'SVM + RBF Kernel'
print(f"mode: {mode}")

try:
    data = fetch_openml(name=data_name, as_frame=True, parser='auto')
    X, y = data.data, data.target

    label_encoder = LabelEncoder()
    y_encoded = label_encoder.fit_transform(y)

    X_encoded = pd.get_dummies(X, columns=['Sex'], drop_first=True)

    X_train, X_test, y_train, y_test = train_test_split(X_encoded, y_encoded, test_size=0.3, random_state=42)

    # Define the model and the parameters for grid search
    svm_model = SVC(kernel='rbf')
    param_grid = {'gamma': ['scale', 'auto'] + [0.01, 0.1, 1, 10, 100]}  # You can add more values for gamma

    grid_search = GridSearchCV(svm_model, param_grid, cv=5)
    grid_search.fit(X_train, y_train)

    # Get the best gamma value
    g = grid_search.best_params_['gamma']
    print(f"Best gamma found: {g}")

    # Use the best model to predict
    y_pred = grid_search.predict(X_test)

    print(classification_report(y_test, y_pred))
    # print(confusion_matrix(y_test, y_pred))

except Exception as e:
    print(f"Error processing {data_name}: {e}")



Processing dataset: abalone
mode: SVM + RBF Kernel


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:311: UserWarning: Multiple active versions of the dataset matching the name abalone exist. Versions may be fundamentally different, returning version 1.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:737: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


Best gamma found: 10
              precision    recall  f1-score   support

           1       0.22      0.45      0.29       191
           2       0.29      0.22      0.25       137
           3       0.14      0.01      0.02        84
           4       0.00      0.00      0.00        53
           5       0.00      0.00      0.00        34
           6       0.00      0.00      0.00        31
           7       0.00      0.00      0.00        21
           8       0.00      0.00      0.00        14
           9       0.00      0.00      0.00        15
          10       0.00      0.00      0.00         8
          12       0.00      0.00      0.00         6
          13       0.00      0.00      0.00         3
          14       0.00      0.00      0.00         3
          15       0.00      0.00      0.00         5
          21       0.00      0.00      0.00         3
          22       0.48      0.68      0.57        19
          23       0.62      0.18      0.28        45
      

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
data_name = 'abalone'
print(f"Processing dataset: {data_name}")


mode = 'SVM + RBF Kernel'
print(f"mode: {mode}")

try:
    data = fetch_openml(name=data_name, version=1, as_frame=True, parser='auto')
    X, y = data.data, data.target

    label_encoder = LabelEncoder()
    y_encoded = label_encoder.fit_transform(y)

    X_encoded = pd.get_dummies(X, columns=['Sex'], drop_first=True)

    X_train, X_test, y_train, y_test = train_test_split(X_encoded, y_encoded, test_size=0.3, random_state=42)

    svm_model = SVC(kernel='rbf', gamma='scale')
    svm_model.fit(X_train, y_train)

    y_pred = svm_model.predict(X_test)

    print(classification_report(y_test, y_pred))
    #print(confusion_matrix(y_test, y_pred))

except Exception as e:
    print(f"Error processing {data_name}: {e}")



Processing dataset: abalone
mode: SVM + RBF Kernel
              precision    recall  f1-score   support

           1       0.25      0.35      0.29       191
           2       0.27      0.23      0.25       137
           3       0.00      0.00      0.00        84
           4       0.00      0.00      0.00        53
           5       0.00      0.00      0.00        34
           6       0.00      0.00      0.00        31
           7       0.00      0.00      0.00        21
           8       0.00      0.00      0.00        14
           9       0.00      0.00      0.00        15
          10       0.00      0.00      0.00         8
          12       0.00      0.00      0.00         6
          13       0.00      0.00      0.00         3
          14       0.00      0.00      0.00         3
          15       0.00      0.00      0.00         5
          21       0.00      0.00      0.00         3
          22       0.17      0.05      0.08        19
          23       0.00      0

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:

mode =  'RBFSampler approximation + SVM'
print(f"mode: {mode}")


from sklearn.kernel_approximation import RBFSampler
from sklearn.pipeline import make_pipeline




try:
    data = fetch_openml(name=data_name, version=1, as_frame=True, parser='auto')
    X, y = data.data, data.target

    label_encoder = LabelEncoder()
    y_encoded = label_encoder.fit_transform(y)

    # One-hot encode the 'sex' feature
    X_encoded = pd.get_dummies(X, columns=['Sex'], drop_first=True)

    X_train, X_test, y_train, y_test = train_test_split(X_encoded, y_encoded, test_size=0.3, random_state=42)

    # Create an RBFSampler for approximating the RBF kernel
    rbf_sampler = RBFSampler(gamma=10.0, n_components=100, random_state=42)

    # Create a pipeline with scaling and SVM
    svm_pipeline = make_pipeline(StandardScaler(), rbf_sampler, SVC(kernel='linear'))

    svm_pipeline.fit(X_train, y_train)

    y_pred = svm_pipeline.predict(X_test)

    print(classification_report(y_test, y_pred))
    #print(confusion_matrix(y_test, y_pred))

except Exception as e:
    print(f"Error processing {data_name}: {e}")



mode: RBFSampler approximation + SVM
              precision    recall  f1-score   support

           1       0.17      0.31      0.22       191
           2       0.17      0.17      0.17       137
           3       0.00      0.00      0.00        84
           4       0.00      0.00      0.00        53
           5       0.00      0.00      0.00        34
           6       0.00      0.00      0.00        31
           7       0.00      0.00      0.00        21
           8       0.00      0.00      0.00        14
           9       0.00      0.00      0.00        15
          10       0.00      0.00      0.00         8
          12       0.00      0.00      0.00         6
          13       0.00      0.00      0.00         3
          14       0.00      0.00      0.00         3
          15       0.00      0.00      0.00         5
          21       0.00      0.00      0.00         3
          22       0.36      0.42      0.39        19
          23       0.32      0.13      0.19 

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
mode = 'Nystroem approximation + SVM'
print(f"mode: {mode}")

try:
    data = fetch_openml(name=data_name, version=1, as_frame=True, parser='auto')
    X, y = data.data, data.target

    label_encoder = LabelEncoder()
    y_encoded = label_encoder.fit_transform(y)

    # One-hot encode the 'sex' feature
    X_encoded = pd.get_dummies(X, columns=['Sex'], drop_first=True)

    X_train, X_test, y_train, y_test = train_test_split(X_encoded, y_encoded, test_size=0.3, random_state=42)

    nystroem = Nystroem(kernel='rbf', gamma=10, n_components=100, random_state=42)

    svm_model = make_pipeline(StandardScaler(), nystroem, SVC(kernel='linear'))

    svm_model.fit(X_train, y_train)
    y_pred = svm_model.predict(X_test)

    print(classification_report(y_test, y_pred))
    #print(confusion_matrix(y_test, y_pred))

except Exception as e:
    print(f"Error processing {data_name}: {e}")

mode: Nystroem approximation + SVM
              precision    recall  f1-score   support

           1       0.11      0.01      0.02       191
           2       0.00      0.00      0.00       137
           3       0.00      0.00      0.00        84
           4       0.00      0.00      0.00        53
           5       0.00      0.00      0.00        34
           6       0.00      0.00      0.00        31
           7       0.00      0.00      0.00        21
           8       0.00      0.00      0.00        14
           9       0.00      0.00      0.00        15
          10       0.00      0.00      0.00         8
          12       0.00      0.00      0.00         6
          13       0.00      0.00      0.00         3
          14       0.00      0.00      0.00         3
          15       0.00      0.00      0.00         5
          21       0.00      0.00      0.00         3
          22       0.38      0.32      0.34        19
          23       0.31      0.11      0.16   

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#  pima dataset

In [ ]:
from sklearn import svm
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

datasets = {
    'abalone': ('abalone', 'target'),
    'image': ('segment', 'class'),
    'pima': ('diabetes', 'class'),
    'waveform': ('waveform-5000', 'class')
}

data_name = 'pima'
print(f"Processing dataset: {data_name}")
results_list = []

try:
    # Fetch the dataset
    data = fetch_openml(name='diabetes', as_frame=True, parser='auto')
    X, y = data.data, data.target

    # Split the dataset
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

    # Define the SVM model and the parameters for grid search
    svm_model = SVC(kernel='rbf')
    param_grid = {'gamma': ['scale', 'auto'] + [0.01, 0.1, 1, 10, 100]}  # You can add more values for gamma

    grid_search = GridSearchCV(svm_model, param_grid, cv=5)
    grid_search.fit(X_train, y_train)

    # Get the best gamma value
    g = grid_search.best_params_['gamma']
    print(f"Best gamma found: {g}")

    # Use the best model to predict
    y_pred = grid_search.predict(X_test)

    # Output evaluation metrics
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))

    # Store results
    results_list.append((data_name, classification_report(y_test, y_pred, output_dict=True), confusion_matrix(y_test, y_pred)))

except Exception as e:
    print(f"Error processing {data_name}: {e}")


Processing dataset: pima


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:311: UserWarning: Multiple active versions of the dataset matching the name diabetes exist. Versions may be fundamentally different, returning version 1.
  warn(


Best gamma found: scale
                 precision    recall  f1-score   support

tested_negative       0.76      0.87      0.81       151
tested_positive       0.66      0.49      0.56        80

       accuracy                           0.74       231
      macro avg       0.71      0.68      0.69       231
   weighted avg       0.73      0.74      0.72       231

[[131  20]
 [ 41  39]]


In [ ]:
datasets = {
    'abalone': ('abalone', 'target'),
    'image': ('segment', 'class'),
    'pima': ('diabetes', 'class'),
    'waveform': ('waveform-5000', 'class')
}


data_name = 'pima'
print(f"Processing dataset: {data_name}")
results_list = []


try:

      data = fetch_openml(name='diabetes', version=1, as_frame=True, parser='auto')
      X, y = data.data, data.target


      X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

      svm_model = SVC(kernel='rbf', gamma='scale')
      svm_model.fit(X_train, y_train)

      y_pred = svm_model.predict(X_test)

      # Output evaluation metrics
      print(classification_report(y_test, y_pred))
      #print(confusion_matrix(y_test, y_pred))

      kernel_matrix = svm_model.decision_function(X_test)
      #print("Kernel matrix (decision function values):")
      #print(kernel_matrix)

      results_list.append((dataset_name, classification_report(y_test, y_pred, output_dict=True), confusion_matrix(y_test, y_pred)))

except Exception as e:
      print(f"Error processing {data_name}: {e}")




Processing dataset: pima
                 precision    recall  f1-score   support

tested_negative       0.76      0.87      0.81       151
tested_positive       0.66      0.49      0.56        80

       accuracy                           0.74       231
      macro avg       0.71      0.68      0.69       231
   weighted avg       0.73      0.74      0.72       231

Error processing pima: name 'dataset_name' is not defined


In [ ]:
mode =  'RBFSampler approximation + SVM'
print(f"mode: {mode}")

from sklearn.kernel_approximation import RBFSampler
try:

        data = fetch_openml(name='diabetes', version=1, as_frame=True, parser='auto')
        X, y = data.data, data.target

        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

        rbf_sampler = RBFSampler(gamma='scale', n_components=100, random_state=42)
        svm_pipeline = make_pipeline(StandardScaler(), rbf_sampler, SVC(kernel='linear'))

        svm_pipeline.fit(X_train, y_train)
        y_pred = svm_pipeline.predict(X_test)

        print(classification_report(y_test, y_pred))
        #print(confusion_matrix(y_test, y_pred))

        results_list.append((data_name, classification_report(y_test, y_pred, output_dict=True), confusion_matrix(y_test, y_pred)))

except Exception as e:
        print(f"Error processing {data_name}: {e}")


mode: RBFSampler approximation + SVM
                 precision    recall  f1-score   support

tested_negative       0.77      0.83      0.80       151
tested_positive       0.63      0.53      0.57        80

       accuracy                           0.73       231
      macro avg       0.70      0.68      0.69       231
   weighted avg       0.72      0.73      0.72       231



In [ ]:
mode = 'Nystroem approximation + SVM'
print(f"mode: {mode}")

try:
        # Load data
        data = fetch_openml(name='diabetes', version=1, as_frame=True, parser='auto')
        X, y = data.data, data.target



        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

        nystroem = Nystroem(kernel='rbf', gamma='scale', n_components=100, random_state=42)
        svm_model = make_pipeline(StandardScaler(), nystroem, SVC(kernel='linear'))
        svm_pipeline.fit(X_train, y_train)

        y_pred = svm_pipeline.predict(X_test)
        print(classification_report(y_test, y_pred))
        #print(confusion_matrix(y_test, y_pred))

        results_list.append((data_name, classification_report(y_test, y_pred, output_dict=True), confusion_matrix(y_test, y_pred)))

except Exception as e:
        print(f"Error processing {data_name}: {e}")


mode: Nystroem approximation + SVM
                 precision    recall  f1-score   support

tested_negative       0.77      0.83      0.80       151
tested_positive       0.63      0.53      0.57        80

       accuracy                           0.73       231
      macro avg       0.70      0.68      0.69       231
   weighted avg       0.72      0.73      0.72       231



# image dataset

In [ ]:
data = fetch_openml(name=data_name, version=1, as_frame=True, parser='auto')

print(f"X shape: {X.shape}, y shape: {y.shape}")


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:999: UserWarning: Version 1 of dataset pima is inactive, meaning that issues have been found in the dataset. Try using a newer version from this URL: https://api.openml.org/data/v1/download/4965316/pima.arff
  warn(


X shape: (768, 8), y shape: (768,)


In [ ]:
from sklearn import svm
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

data_name = 'image'
print(f"Processing dataset: {data_name}")
results_list = []

try:
    # Fetch the dataset
    data = fetch_openml(name='segment', as_frame=True, parser='auto')
    X, y = data.data, data.target.squeeze()

    # Split the dataset
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

    # Define the SVM model and the parameters for grid search
    svm_model = SVC(kernel='rbf')
    param_grid = {'gamma': ['scale', 'auto'] + [0.01, 0.1, 1, 10, 100]}  # You can add more values for gamma

    grid_search = GridSearchCV(svm_model, param_grid, cv=5)
    grid_search.fit(X_train, y_train)

    # Get the best gamma value
    g = grid_search.best_params_['gamma']
    print(f"Best gamma found: {g}")

    # Use the best model to predict
    y_pred = grid_search.predict(X_test)

    # Output evaluation metrics
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))

    # Store results
    results_list.append((data_name, classification_report(y_test, y_pred, output_dict=True), confusion_matrix(y_test, y_pred)))

except Exception as e:
    print(f"Error processing {data_name}: {e}")


Processing dataset: image


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:311: UserWarning: Multiple active versions of the dataset matching the name segment exist. Versions may be fundamentally different, returning version 1.
  warn(


Best gamma found: 0.01
              precision    recall  f1-score   support

   brickface       0.99      0.91      0.95        86
      cement       0.53      0.98      0.69       103
     foliage       0.93      0.68      0.79       111
       grass       1.00      0.84      0.91        95
        path       1.00      0.84      0.91        99
         sky       1.00      0.89      0.94        89
      window       0.90      0.81      0.85       110

    accuracy                           0.85       693
   macro avg       0.91      0.85      0.86       693
weighted avg       0.90      0.85      0.86       693

[[ 78   7   1   0   0   0   0]
 [  1 101   0   0   0   0   1]
 [  0  26  76   0   0   0   9]
 [  0  15   0  80   0   0   0]
 [  0  16   0   0  83   0   0]
 [  0  10   0   0   0  79   0]
 [  0  16   5   0   0   0  89]]


In [ ]:
data_name = 'image'
print(f"Processing dataset: {data_name}")
results_list = []




try:
      data = fetch_openml(name='segment', as_frame=True, parser='auto')
      X, y = data.data, data.target.squeeze()

      X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

      svm_model = SVC(kernel='rbf', gamma='scale')
      svm_model.fit(X_train, y_train)

      y_pred = svm_model.predict(X_test)

      # Output evaluation metrics
      print(classification_report(y_test, y_pred))
      #print(confusion_matrix(y_test, y_pred))

      kernel_matrix = svm_model.decision_function(X_test)
      #print("Kernel matrix (decision function values):")
      #print(kernel_matrix)

      results_list.append((dataset_name, classification_report(y_test, y_pred, output_dict=True), confusion_matrix(y_test, y_pred)))

except Exception as e:
      print(f"Error processing {data_name}: {e}")




Processing dataset: image
              precision    recall  f1-score   support

   brickface       0.89      0.73      0.80        86
      cement       0.91      0.87      0.89       103
     foliage       0.69      0.85      0.76       111
       grass       0.99      1.00      0.99        95
        path       0.99      1.00      0.99        99
         sky       1.00      1.00      1.00        89
      window       0.71      0.65      0.68       110

    accuracy                           0.87       693
   macro avg       0.88      0.87      0.87       693
weighted avg       0.87      0.87      0.87       693

Error processing image: name 'dataset_name' is not defined


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:311: UserWarning: Multiple active versions of the dataset matching the name segment exist. Versions may be fundamentally different, returning version 1.
  warn(


In [ ]:
mode =  'RBFSampler approximation + SVM'
print(f"mode: {mode}")

from sklearn.kernel_approximation import RBFSampler
try:
        data = fetch_openml(name='segment', version=1, as_frame=True, parser='auto')
        X, y = data.data, data.target


        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
        rbf_sampler = RBFSampler(gamma=0.01, n_components=100, random_state=42)

        svm_pipeline = make_pipeline(StandardScaler(), rbf_sampler, SVC(kernel='linear'))
        svm_pipeline.fit(X_train, y_train)
        y_pred = svm_pipeline.predict(X_test)

        # Output evaluation metrics
        print(classification_report(y_test, y_pred))
        #print(confusion_matrix(y_test, y_pred))

        results_list.append((data_name, classification_report(y_test, y_pred, output_dict=True), confusion_matrix(y_test, y_pred)))

except Exception as e:
        print(f"Error processing {data_name}: {e}")


mode: RBFSampler approximation + SVM
              precision    recall  f1-score   support

   brickface       0.95      0.98      0.97        86
      cement       0.82      0.86      0.84       103
     foliage       0.76      0.83      0.79       111
       grass       1.00      0.99      0.99        95
        path       0.92      0.99      0.95        99
         sky       1.00      1.00      1.00        89
      window       0.79      0.62      0.69       110

    accuracy                           0.89       693
   macro avg       0.89      0.90      0.89       693
weighted avg       0.88      0.89      0.88       693



In [ ]:
mode = 'Nystroem approximation + SVM'
print(f"mode: {mode}")

try:
        data = fetch_openml(name='segment', version=1, as_frame=True, parser='auto')
        X, y = data.data, data.target


        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
        nystroem = Nystroem(kernel='rbf', gamma=0.01, n_components=100, random_state=42)
        svm_model = make_pipeline(StandardScaler(), nystroem, SVC(kernel='linear'))
        svm_pipeline.fit(X_train, y_train)
        y_pred = svm_pipeline.predict(X_test)

        # Output evaluation metrics
        print(classification_report(y_test, y_pred))
        #print(confusion_matrix(y_test, y_pred))

        results_list.append((data_name, classification_report(y_test, y_pred, output_dict=True), confusion_matrix(y_test, y_pred)))

except Exception as e:
        print(f"Error processing {data_name}: {e}")


mode: Nystroem approximation + SVM
              precision    recall  f1-score   support

   brickface       0.95      0.98      0.97        86
      cement       0.82      0.86      0.84       103
     foliage       0.76      0.83      0.79       111
       grass       1.00      0.99      0.99        95
        path       0.92      0.99      0.95        99
         sky       1.00      1.00      1.00        89
      window       0.79      0.62      0.69       110

    accuracy                           0.89       693
   macro avg       0.89      0.90      0.89       693
weighted avg       0.88      0.89      0.88       693



# waveform dataset

In [ ]:
from sklearn import svm
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

data_name = 'waveform'
print(f"Processing dataset: {data_name}")
results_list = []

try:
    # Fetch the dataset
    data = fetch_openml(name='waveform-5000', as_frame=True, parser='auto')
    X, y = data.data, data.target.squeeze()

    # Split the dataset
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

    # Define the SVM model and the parameters for grid search
    svm_model = SVC(kernel='rbf')
    param_grid = {'gamma': ['scale', 'auto'] + [0.01, 0.1, 1, 10, 100]}  # You can add more values for gamma

    grid_search = GridSearchCV(svm_model, param_grid, cv=5)
    grid_search.fit(X_train, y_train)

    # Get the best gamma value
    g = grid_search.best_params_['gamma']
    print(f"Best gamma found: {g}")

    # Use the best model to predict
    y_pred = grid_search.predict(X_test)

    # Output evaluation metrics
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))

    # Store results
    results_list.append((data_name, classification_report(y_test, y_pred, output_dict=True), confusion_matrix(y_test, y_pred)))

except Exception as e:
    print(f"Error processing {data_name}: {e}")


Processing dataset: waveform


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:311: UserWarning: Multiple active versions of the dataset matching the name waveform-5000 exist. Versions may be fundamentally different, returning version 1.
  warn(


Best gamma found: scale
              precision    recall  f1-score   support

           0       0.88      0.85      0.87       513
           1       0.87      0.90      0.88       481
           2       0.88      0.87      0.88       506

    accuracy                           0.88      1500
   macro avg       0.88      0.88      0.88      1500
weighted avg       0.88      0.88      0.88      1500

[[438  36  39]
 [ 26 434  21]
 [ 34  31 441]]


In [ ]:
data_name = 'waveform'
print(f"Processing dataset: {data_name}")
results_list = []




try:
      data = fetch_openml(name='waveform-5000', as_frame=True, parser='auto')
      X, y = data.data, data.target.squeeze()

      X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

      svm_model = SVC(kernel='rbf', gamma='0.1')
      svm_model.fit(X_train, y_train)

      y_pred = svm_model.predict(X_test)

      # Output evaluation metrics
      print(classification_report(y_test, y_pred))
      #print(confusion_matrix(y_test, y_pred))

      kernel_matrix = svm_model.decision_function(X_test)
      #print("Kernel matrix (decision function values):")
      #print(kernel_matrix)

      results_list.append((dataset_name, classification_report(y_test, y_pred, output_dict=True), confusion_matrix(y_test, y_pred)))

except Exception as e:
      print(f"Error processing {data_name}: {e}")




Processing dataset: waveform
Error processing waveform: The 'gamma' parameter of SVC must be a str among {'auto', 'scale'} or a float in the range [0.0, inf). Got '0.1' instead.


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:311: UserWarning: Multiple active versions of the dataset matching the name waveform-5000 exist. Versions may be fundamentally different, returning version 1.
  warn(


In [ ]:
mode =  'RBFSampler approximation + SVM'
print(f"mode: {mode}")

from sklearn.kernel_approximation import RBFSampler
try:
        data = fetch_openml(name='waveform-5000', version=1, as_frame=True, parser='auto')
        X, y = data.data, data.target


        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
        rbf_sampler = RBFSampler(gamma='scale', n_components=100, random_state=42)

        svm_pipeline = make_pipeline(StandardScaler(), rbf_sampler, SVC(kernel='linear'))
        svm_pipeline.fit(X_train, y_train)
        y_pred = svm_pipeline.predict(X_test)

        # Output evaluation metrics
        print(classification_report(y_test, y_pred))
        #print(confusion_matrix(y_test, y_pred))

        results_list.append((data_name, classification_report(y_test, y_pred, output_dict=True), confusion_matrix(y_test, y_pred)))

except Exception as e:
        print(f"Error processing {data_name}: {e}")


mode: RBFSampler approximation + SVM
              precision    recall  f1-score   support

           0       0.75      0.70      0.72       513
           1       0.75      0.77      0.76       481
           2       0.78      0.80      0.79       506

    accuracy                           0.76      1500
   macro avg       0.76      0.76      0.76      1500
weighted avg       0.76      0.76      0.76      1500



In [ ]:
mode = 'Nystroem approximation + SVM'

print(f"mode: {mode}")

from sklearn.kernel_approximation import RBFSampler
try:
        data = fetch_openml(name='waveform-5000', version=1, as_frame=True, parser='auto')
        X, y = data.data, data.target


        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
        nystroem = Nystroem(kernel='rbf', gamma='scale', n_components=100, random_state=42)
        svm_model = make_pipeline(StandardScaler(), nystroem, SVC(kernel='linear'))
        svm_pipeline.fit(X_train, y_train)
        y_pred = svm_pipeline.predict(X_test)

        # Output evaluation metrics
        print(classification_report(y_test, y_pred))
        #print(confusion_matrix(y_test, y_pred))

        results_list.append((data_name, classification_report(y_test, y_pred, output_dict=True), confusion_matrix(y_test, y_pred)))

except Exception as e:
        print(f"Error processing {data_name}: {e}")


mode: Nystroem approximation + SVM
              precision    recall  f1-score   support

           0       0.75      0.70      0.72       513
           1       0.75      0.77      0.76       481
           2       0.78      0.80      0.79       506

    accuracy                           0.76      1500
   macro avg       0.76      0.76      0.76      1500
weighted avg       0.76      0.76      0.76      1500

